execute as @s[scores={hb=15}] run replaceitem entity @s slot.weapon.mainhand 0 diamond_sword 1
execute as @s[scores={hb=14}] run replaceitem entity @s slot.weapon.mainhand 0 golden_sword 1
execute as @s[scores={hb=13}] run replaceitem entity @s slot.weapon.mainhand 0 iron_sword 1
execute as @s[scores={hb=12}] run replaceitem entity @s slot.weapon.mainhand 0 stone_sword 1
execute as @s[scores={hb=11}] run replaceitem entity @s slot.weapon.mainhand 0 wooden_sword 1
execute as @s[scores={hb=10}] run replaceitem entity @s slot.weapon.mainhand 0 diamond_axe 1
execute as @s[scores={hb=9}] run replaceitem entity @s slot.weapon.mainhand 0 golden_axe 1
execute as @s[scores={hb=8}] run replaceitem entity @s slot.weapon.mainhand 0 iron_axe 1
execute as @s[scores={hb=7}] run replaceitem entity @s slot.weapon.mainhand 0 stone_axe 1
execute as @s[scores={hb=6}] run replaceitem entity @s slot.weapon.mainhand 0 wooden_axe 1
execute as @s[scores={hb=5}] run replaceitem entity @s slot.weapon.mainhand 0 diamond_shovel 1
execute as @s[scores={hb=4}] run replaceitem entity @s slot.weapon.mainhand 0 golden_shovel 1
execute as @s[scores={hb=3}] run replaceitem entity @s slot.weapon.mainhand 0 iron_shovel 1
execute as @s[scores={hb=2}] run replaceitem entity @s slot.weapon.mainhand 0 stone_shovel 1
execute as @s[scores={hb=1}] run replaceitem entity @s slot.weapon.mainhand 0 wooden_shovel 1
